### ISSUE TITLE
Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by rohitpaniker** [CrystallizeAPI/furniture-nextjs#1]
Hello folks,

lovely work you guys are doing there.

I am facing an issue. After doing NPM INSTALL and when I do `npm run dev` for a quick run. I am getting the following error:

`Cannot read properties of null (reading 'map')`

Looks like it is seeking api-key from .env file.

It would be great if you could provide a sample .env file too with this repo which can be used to quickly run the application and see before starting to work on it. :)

**Comment by Zhenvip** [comment]
I got this issue too. never fixed
